name: build-jetbrains-plugin
on: 
  push:
    paths:
     - 'plugins/jetbrains/'
     - '.github/workflows/build-jetbrains-plugin.yml'
    tags-ignore:
      - '**'
  workflow_dispatch:
    inputs:
      event_type:
        description: "Trigger event type"
        required: false
      debug:
        description: 'debug mode boolean'
        required: false
        default: 'false'
jobs:
  build-jetbrains-plugin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
    defaults:
      run:
        working-directory: 'plugins/jetbrains/'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download WhaleLint binary
        if: ${{ github.event.pr }} || ${{ github.event.pr_merge }}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: whalelint-${{ github.sha }} ${{ runner.os }}
          path: ${{ github.workspace }}/
          workflow: build.yml
          workflow_conclusion: success
      - name: Rename binary
        if: ${{ github.event.event_type }} == "push_to_main" || ${{ github.event.event_type }} == "pr"
        run: mv ${{ github.workspace }}/whalelint-${{ github.sha }} ${{ github.workspace }}/whalelint
      - name: Add run permission to WhaleLint binary
        if: ${{ github.event.pr }} || ${{ github.event.pr_merge }}
        run: chmod +x ${{ github.workspace }}/whalelint
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: Verify plugin
        run: ./gradlew buildPlugin
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Read version
        id: read_version
        run: |
          echo ::set-output name=semanticVersion::$(./gradlew properties | grep version | cut -d" " -f2-)
      - name: Upload JetBrains Plugin Artifact
        if: ${{ github.event.inputs.event_type }} == "push_to_main" || github.base_ref == 'main' || github.ref == 'refs/heads/main' 
        uses: actions/upload-artifact@v2
        with:
          name: whalelint-${{ github.sha }} JetBrainsPlugin ${{ runner.os }}
          path: ${{ github.workspace }}/plugins/jetbrains/build/distributions/whalelint-${{ steps.read_version.outputs.semanticVersion }}.zip
          retention-days: 7
          