name: build-go
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'
  #   tags-ignore:
  #     - '**'
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15.6' # The Go version to download (if necessary) and use.

      - name: Cache Go modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go

      - name: Go build
        run: go build -ldflags "-w -s" -o "whalelint-${{ github.sha }}"
        env: 
          CGO_ENABLED: 0
          OS: ${{ runner.os }}
      
      - name: Run tests
        run: go test -v -cover ./...

      - name: Upload WhaleLint bin to Artifacts
        # if:   ${{ github.base_ref }} == 'main'
        uses: actions/upload-artifact@v2
        with:
          name: whalelint-${{ github.sha }} ${{ runner.os }}
          path: ${{ github.workspace }}/whalelint-${{ github.sha }}
          retention-days: 7
        
  lint:
    name: lint
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
