name: build-vscode-extension
on:
  push:
    paths:
     - 'plugins/vscode/'
     - '.github/workflows/build-vscode-extension.yml'
    tags-ignore:
      - '**'
  repository_dispatch:
    types: 
      - pr
      - pr_merge
jobs:
  build-vscode-extension:
    defaults:
      run:
        working-directory: 'plugins/vscode/'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.6.0
          check-latest: true
      - name: Copy WhaleLint binary into extension folder
        if: ${{ github.event.pr }} || ${{ github.event.pr_merge }}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: whalelint-${{ github.sha }} ${{ runner.os }}
          path: plugins/vscode/whalelint
          workflow: build.yml
      - name: Add run permission to WhaleLint binary
        if: ${{ github.event.pr }} || ${{ github.event.pr_merge }}
        run: chmod +x plugins/vscode/whalelint
      - run: |
          npm install && \
          npm install -g vsce && \
          vsce package -o whalelint-${{ github.sha }}.vsix
      # if:   ${{ github.base_ref }} == 'main' - TODO
      - name: Upload VSCode Extension Artifact
        if: ${{ github.event.pr }} || ${{ github.event.pr_merge }}
        uses: actions/upload-artifact@v2
        with:
          name: whalelint-${{ github.sha }} VSCodeExtension ${{ runner.os }}
          path: ${{ github.workspace }}/plugins/vscode/whalelint-${{ github.sha }}.vsix
          retention-days: 7