name: build-go
on: 
  push:
    # branches:
    #   - '**'
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - 'main'
    tags-ignore:
      - '**'
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15.6' # The Go version to download (if necessary) and use.

      - name: Cache Go modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go

      - name: Go build
        run: go build -ldflags "-w -s" -o "whalelint-${{ github.sha }}"
        env: 
          CGO_ENABLED: 0
          OS: ${{ runner.os }}
      
      - name: Run tests
        run: go test -v -cover ./...

      - run: echo "REF is ${{ github.ref }}"
      - run: echo "BASE REF is ${{ github.base_ref }}"

      - name: Upload WhaleLint bin to Artifacts
        if: github.base_ref == 'main'
        uses: actions/upload-artifact@v2
        with:
          name: whalelint-${{ github.sha }} ${{ runner.os }}
          path: ${{ github.workspace }}/whalelint-${{ github.sha }}
          retention-days: 7

  vscode:
    name: vscode-trigger
    needs: build_and_test
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Triggen VSCode extension build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WHALELINT_WORKFLOW }}
          event-type: pr
          client-payload: '{"base_ref": "${{ github.base_ref }}", "sha": "${{ github.sha }}", "runner.os": "${{ runner.os }}" }'
        
  lint:
    name: lint
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
