name: release
on:
  push:
    # tags: 
    #   - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Get version fallback
        run: echo "RELEASE_VERSION=last_ci_build" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v') == false
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build WhaleLint Engine Docker image
        run: |
          docker build -f docker/Dockerfile . -t ghcr.io/cremindes/whalelint:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/cremindes/whalelint:${{ env.RELEASE_VERSION }}
        