name: release
on:
  push:
    # tags: 
    #   - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Get version fallback  # used for debugging
        run: echo "RELEASE_VERSION=last_ci_build" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v') == false
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      # WhaleLint Engine + Docker image
      - name: Build WhaleLint Engine Docker image
        run: |
          docker build -f docker/Dockerfile . -t ghcr.io/cremindes/whalelint:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/cremindes/whalelint:${{ env.RELEASE_VERSION }}
      - name: Prepare further steps
        run: |
          # copy WhaleLint Engine from previously built Docker image
          image=$(docker create ghcr.io/cremindes/whalelint:latest)
          docker cp $image:/usr/local/bin/whalelint ./;
          docker rm $image;
          # copy WhaleLint Engine binary to plugin folders
          cp whalelint plugins/vscode/
          cp whalelint plugins/jetbrains/
      - name: Upload WhaleLint Engine as release artifact
        run: |
          echo "TODO"
      # Build VSCode extension
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: npm install && npm install -g vsce
        working-directory: ./plugins/vscode
      - name: Generate static files
        run: |
          cp ../../LICENSE ./
          cp ../../CHANGELOG.md ./
          convert -quiet -background none -trim -size 128 ../../docs/icon.svg ./icon.png || true
        working-directory: ./plugins/vscode
      - name: Build VSCode extension
        run: vsce package && ls -lah
        working-directory: ./plugins/vscode
      - name: Publish VSCode extension
        run: vsce publish -i "whalelint-$RELEASE_VERSION.vsix"
        working-directory: ./plugins/vscode
        env:
          VSCE_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        if: success() && startsWith( github.ref, 'refs/tags/v')
      - name: Upload VSCode extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: whalelint-${{ github.sha }} JetBrainsPlugin ${{ runner.os }}
          path: ${{ github.workspace }}/plugins/vscode/dist/whalelint-v0.0.8.zip
          retention-days: 7
      # JetBrains plugin
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew buildPlugin
        working-directory: ./plugins/jetbrains
      - name: Verify plugin
        run: ./gradlew buildPlugin
        working-directory: ./plugins/jetbrains
      - name: Cleanup Gradle cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Read version
        id: read_version
        run: |
          echo ::set-output name=semanticVersion::$(./gradlew properties | grep version | cut -d" " -f2-)
      - name: Upload JetBrains plugin aArtifact
        uses: actions/upload-artifact@v2
        with:
          name: whalelint-${{ github.sha }} JetBrainsPlugin ${{ runner.os }}
          path: ${{ github.workspace }}/plugins/jetbrains/build/distributions/whalelint-${{ steps.read_version.outputs.semanticVersion }}.zip
          retention-days: 7